# Generated by Django 2.1.15 on 2022-04-12 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEjecucion',
            fields=[
                ('ID_DETALLE_EJECUCION', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID_DETALLE_EJECUCION')),
                ('FECHA', models.DateField()),
                ('ESTADO_EJECUCION', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-FECHA',),
            },
        ),
        migrations.CreateModel(
            name='EjecucionHoy',
            fields=[
                ('ID_PROCESO', models.IntegerField(primary_key=True, serialize=False)),
                ('FECHA', models.DateField()),
                ('ESTADO_EJECUCION', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('ID_INCIDENTE', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID_INCIDENTE')),
                ('PROBLEMA', models.CharField(blank=True, max_length=500, null=True)),
                ('CAUSA', models.CharField(blank=True, max_length=500, null=True)),
                ('IMPACTO', models.CharField(blank=True, max_length=500, null=True)),
                ('SOLUCION', models.CharField(blank=True, max_length=500, null=True)),
                ('FECHA_HORA_SOLUCION', models.DateTimeField(blank=True, null=True)),
                ('RESOLUTOR', models.CharField(blank=True, max_length=500, null=True)),
                ('FECHA_HORA_REEJECUCION', models.DateTimeField(blank=True, null=True)),
                ('ESTADO_REEJECUCION', models.CharField(blank=True, max_length=50, null=True)),
                ('ID_DETALLE_EJECUCION', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TBMD.DetalleEjecucion')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('ID_PROCESO', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID_PROCESO')),
                ('NOMBRE_PROCESO', models.CharField(blank=True, max_length=150, null=True)),
                ('TIPO_PROCESO', models.CharField(blank=True, max_length=50, null=True)),
                ('HORA_EJECUCION', models.TimeField()),
                ('PERIODICIDAD', models.CharField(blank=True, max_length=50, null=True)),
                ('SERVIDOR', models.CharField(blank=True, max_length=50, null=True)),
                ('ACTIVO', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='detalleejecucion',
            name='ID_PROCESO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TBMD.Proceso'),
        ),
    ]
